<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>UNDRR - Home Page</title>
	<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
	<link rel="stylesheet" href="//unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.css" />
	<link rel="stylesheet" href="//unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.Default.css" />
	<?php include('../menu.html') ?>
</head>

<body>
	<h1 style="text-align: center;margin-top:20px;"> <b>What are Tsunamis?</b></h1> <br>
	<p style="margin-left: 5%;margin-right:5%;">The phenomenon we call tsunami is a series of large waves of extremely long wavelength and period usually generated by a violent, impulsive undersea disturbance or activity near the coast or in the ocean. <br> When a sudden displacement of a large volume of water occurs, or if the sea floor is suddenly raised or dropped by an earthquake, big tsunami waves can be formed. <br> The waves travel out of the area of origin and can be extremely dangerous and damaging when they reach the shore. <br>
		Tsunami waves often look like walls of water and can attack the shoreline and be dangerous for hours, with waves coming every 5 to 60 minutes. The first wave may not be the largest, and often it is the 2nd, 3rd, 4th or even later waves that are the biggest. <br> After one wave inundates, or floods inland, it recedes seaward often as far as a person can see so the seafloor is exposed.</p>
	<br> <br>
	<video controls src="Tsunamis.mp4" width="90%" height="80%" style="margin-left: 5%;"></video>
	<div class="bg-dark text-secondary px-4 py-5 text-center">
		<div class="py-5">
			<h2 class="display-5 fw-bold text-white">An Informative Graphic</h2>
			<div class="col-lg-16 text-center mx-auto">
				<p class=" text-center fs-5 mb-4">Here is a graphic that shows the frequency of tsunamis between 2000 and 2021. <br>
				<div class="chart-container"></div>
			</div>
		</div>
	</div>
	<div class="container col-xxl-16 px-2 py-5">
		<div class="row flex-lg-row g-5 py-5">
			<div class="col-8">
				<div id="yass">
					<label for="data">Select which data to display </label>
					<select id="data">
						<option value="displayTsunamis">Show Tsunamis</option>
						<option value="HideTsunamis">Hide Tsunamis</option>
					</select>
				</div>
				<div id="map" class=" mt-2 rounded"> </div>
			</div>

			<div class="col-4">
				<div class="d-grid gap-2">
					<a class="btn btn-outline-info btn-lg me-sm-3 fw-bold" id="btn" style="display: none;">Click me to show details</a>
					<div id="d1" style="display: none;">
						<h2></h2>
						<p></p>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
<?php include('../footer.html'); ?>

</html>
<script src="//d3js.org/d3.v7.min.js"></script>
<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
<script src="//unpkg.com/leaflet.markercluster@1.4.1/dist/leaflet.markercluster.js"></script>
<script src="./tsunami.js"></script>